tags:
  - name: Persona
    description: Peticiones para realizar sobre personas.

paths:
  /persona/{id}:
    get:
      tags:
        - Persona
      summary: Obtiene una persona por Id.
      description: Obtiene una persona por su Id que recibe por url.
      operationID: getPersonaByPk
      parameters:
        - name: id
          in: path
          description: Id de una persona
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Persona obtenida exitosamente.
        '400':
          description: El Id ingresado es inválido.
        '404':
          description: No se encontró una persona con el Id dado.
        '500':
          description: Error interno del servidor al procesar la solicitud.