version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db_admin_med_integral
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_admin_med_integral
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - medIntegral
  redis:
    image: redis:latest
    container_name: mi-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"] 
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - medIntegral
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: mi-redis-insight
    restart: always
    ports:
      - 5540:5540 
    networks:
      - medIntegral
    volumes:
      - redisinsight_db:/db
volumes:
  postgres_data:
  redis_data: 
  redisinsight_db:
networks:
  medIntegral:
    driver: bridge