version: '3.8'

services:
  postgres:
    image: postgres
    container_name: db_admin_med_integral
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_admin_med_integral
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: